apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: terraform
    terraform.ingress.kubernetes.io/internal: "false"
    # terraform.ingress.kubernetes.io/tcp-configmap: "ingress-tcp-services" # cm name within the ingress namespace
    # terraform.ingress.kubernetes.io/udp-configmap: "ingress-udp-services" # cm name within the ingress namespace
    # terraform.ingress.kubernetes.io/template: "custom-template" cm name within the ingress namespace
  name: test-terraform-ingress
spec:
  rules:
  - host: example.com
    http:
      paths:
      - backend:
          serviceName: my-service
          servicePort: 8080
        path: /foo
  tls:
  - hosts:
    - example.com
    secretName: tls
